### ISSUE TITLE
How do i run examples

### ISSUE THREAD

**Issue by imrying** [milmazz/turtle#1]
Hey,
I am very new in elixir and just stumbled on your code. I have previously used turtle in python. All i want to know is how you run an example. When i type in TurtleUI:
`iex -S mix`

`
iex(1)> TurtleUI.pen_up

:ok

iex(2)> TurtleUI.pen_down

:ok

iex(3)> TurtleUI.Examples.SierpinskiTriangle.run(500,7)

** (UndefinedFunctionError) function TurtleUI.Examples.SierpinskiTriangle.run/2 is undefined (module TurtleUI.Examples.SierpinskiTriangle is not available)
    TurtleUI.Examples.SierpinskiTriangle.run(500, 7)
`

I know this might be a trivial question but i do not know what i am doing wrong.
Thanks in advance

**Comment by milmazz** [comment]
@imrying  I'm just reading about this issue, really sorry about this delay in my response.

But also, I'm really happy to know that someone else tried this 🎉

To answer your question, you need to compile the module `TurtleUI.Examples.SierpinskiTriangle`.

```elixir
Interactive Elixir (1.13.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> TurtleUI.pen_up
:ok
iex(2)> TurtleUI.pen_down
:ok
iex(3)> c "examples/sierpinski_triangle.ex"
[TurtleUI.Examples.SierpinskiTriangle]
iex(4)> TurtleUI.Examples.SierpinskiTriangle.run(500,7)
:ok
```

I will update the `README` to show how to run the examples.

**Comment by imrying** [comment]
This is just awesome! Just ran some of the examples and it is so cool. Will post my review soon ;-)
